name: Run pytest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    name: Run tests using pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.x'

      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt

      -name: Start database
        run: |
          docker compose up -d psotgres
          docker compose exec -T postgres bash -c 'until pg_isready -U test; do sleep 1; done'

      - name: Test with pytest
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db
        run: |
          pytest 

      - name: Cleanup
        if: always()
        run: |
          docker compose down